authorName: Neuromation
experimentName: example_mnist_nni
trialConcurrency: {{ worker_count }}
maxExecDuration: 1h
maxTrialNum: 10
trainingServicePlatform: remote
searchSpacePath: search_space.json
useAnnotation: false
tuner:
  builtinTunerName: TPE
  classArgs:
    optimize_mode: maximize
trial:
  command: python3 mnist.py
  codeDir: ../modules
machineList: {% for worker in workers %}
  - ip: {{ worker }}
    username: root
    sshKeyPath: /id_rsa
    passphrase: neuromation {% endfor %}
